### PR TITLE
Mirror rust setup script for security

### PR DESCRIPTION
**Pull request by mirhagk**
Change `curl | sh` to instead `sh` a mirrored version of the file.

No need to trust https://sh.rustup.sh with build-time shell access.

http://b/238367731

### CODE REVIEW

**Review by rosbo — APPROVED** [review]

**Comment by rosbo** [comment]
Thank you!

**Comment by rosbo** [comment]
Failed with:

```
Step #0 - "build": ADD failed: file not found in build context or excluded by .dockerignore: stat rustup.sh: file does not exist
Step #0 - "build": Step 3/9 : ADD rustup.sh rustup.sh
```

You have a typo in the file you added to the repo. It is named `rushup.sh` instead of `rustup.sh`.

**Comment by mirhagk** [comment]
Ah sorry, I did a couple things after checking that it built, should've caught this. I'll fix

**Pull request merged**
